version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: ./infra/backend/Dockerfile
    container_name: wellbex_backend
    restart: always
    volumes:
      - static:/wellbex-test/static/
    ports:
      - '${PROD_PORT}:8000'
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    container_name: wellbex_db
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 2s
      retries: 3
    volumes:
      - wellbex_data:/var/lib/postgresql/data

  redis:
    container_name: wellbex_redis
    image: redis:7.2.4-alpine
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 5

  flower:
    image: mher/flower
    ports:
      - "${FLOWER_PORT}:5555"
    environment:
      - BROKER_URL=redis://redis:${REDIS_PORT}/0
    depends_on:
      - redis
      - celery_worker
      - celery_beat
      - db
      - backend
    restart:
      always

  celery_worker:
    container_name: wellbex_celery_worker
    restart: always
    build:
      context: .
      dockerfile: ./infra/celery/worker/Dockerfile
    command: celery -A core worker -l info
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend

  celery_beat:
    container_name: wellbex_celery_beat
    restart: always
    build:
      context: .
      dockerfile: ./infra/celery/beat/Dockerfile
    command: celery -A core beat -l info
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend
      - celery_worker


volumes:
  static:
  wellbex_data:
    driver: local
