# Generated by Django 5.0.3 on 2024-03-22 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('state', models.CharField(max_length=100, verbose_name='Штат')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Вес')),
                ('description', models.CharField(max_length=999, verbose_name='Описание')),
                ('location_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_delivery_goods', to='api.location', verbose_name='Локация delivery')),
                ('location_pick_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pick_up_goods', to='api.location', verbose_name='Локация pick-up')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('unique_number', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Unique number not valid', regex='^[0-9]+[0-9]+[A-Z]$')], verbose_name='Уникальный номер')),
                ('carrying', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location_car', to='api.location', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'db_table': 'car',
            },
        ),
    ]
