# Generated by Django 5.0.3 on 2024-03-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_goods_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.PositiveIntegerField(verbose_name='Почтовый индекс'),
        ),
    ]
